<a href="https://colab.research.google.com/github/Vivek-afk81/ml-workshop/blob/main/FFN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## FEED FORWARD

In [1]:
import numpy as np

In [3]:
x= np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y= np.array([
    [1],[1],[0]
])

In [14]:
def sigmoid(x):
  return 1/(1+np.exp(-x))


In [15]:
#input ;ayer neurons will be always equal to the number of columns

inputNeurons=x.shape[1]
#hdden neurons we can decide by hit and trial
hiddenNeurons=4
#output neurns epend upon the number of clsses we have in the target column
outputNeurons= 1

In [16]:
weightsHidden=np.random.uniform(size=(inputNeurons,hiddenNeurons ))
biasHidden=np.random.uniform(size=(1,hiddenNeurons))
weightsOutput=np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput=np.random.uniform(size=(1,outputNeurons))

In [17]:
#feed forwaard
#step 1 apply dot product and add bias : f(x) = x.wh+bias

fx=np.dot(x,weightsHidden) + biasHidden

In [18]:
#Step-2 apply activation function
hiddenLayer=sigmoid(fx)

In [20]:
hiddenLayer

array([[0.81457899, 0.86562306, 0.79277216, 0.76167798],
       [0.88532069, 0.90445186, 0.82923524, 0.77335978],
       [0.8138521 , 0.74426806, 0.8314848 , 0.80222957]])

In [25]:
#Step 3 apply dot product and bias : f(x) = hiddenLayer.wout +biasOut

fx_=np.dot(hiddenLayer,weightsOutput) +biasOutput
fx_

array([[1.61460121],
       [1.66620209],
       [1.61997679]])

In [26]:
biasHidden

array([[0.45384414, 0.58207855, 0.5629876 , 0.3558738 ]])

In [27]:
biasOutput

array([[0.57924846]])

In [28]:
outputLayer=sigmoid(fx_)

In [29]:
outputLayer

array([[0.83404922],
       [0.8410688 ],
       [0.83479193]])

## BACKPROPAGATION


In [30]:
def derivativeSigmoid(x):
  return x* (1-x)

In [31]:
errorOutput = outputLayer - y
slopeOutput = derivativeSigmoid(outputLayer)
deltaOutput = errorOutput * slopeOutput

In [32]:
errorHidden = np.dot(deltaOutput, weightsOutput.T)
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden