<a href="https://colab.research.google.com/github/Vivek-afk81/ml-workshop/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,SimpleRNN
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
text= [
    "i am learning deep learning",
    "i like deep learning",
    "deep learning is fun to learn",
    "i also like machine learning"
]

Tokenization

In [5]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(text)

In [7]:
sequences=tokenizer.texts_to_sequences(text)
print(sequences)

[[2, 5, 1, 3, 1], [2, 4, 3, 1], [3, 1, 6, 7, 8, 9], [2, 10, 4, 11, 1]]


In [14]:
#create input and output pairs

X=[]
y=[]

for seq in sequences:
  for i in range(1,len(seq)):
    X.append(seq[:i])
    y.append(seq[i])

In [15]:
X[1],y[1]

([2, 5], 1)

In [16]:
#Pad sequences
X=pad_sequences(X)
y=np.array(y)

In [17]:
X,y

(array([[ 0,  0,  0,  0,  2],
        [ 0,  0,  0,  2,  5],
        [ 0,  0,  2,  5,  1],
        [ 0,  2,  5,  1,  3],
        [ 0,  0,  0,  0,  2],
        [ 0,  0,  0,  2,  4],
        [ 0,  0,  2,  4,  3],
        [ 0,  0,  0,  0,  3],
        [ 0,  0,  0,  3,  1],
        [ 0,  0,  3,  1,  6],
        [ 0,  3,  1,  6,  7],
        [ 3,  1,  6,  7,  8],
        [ 0,  0,  0,  0,  2],
        [ 0,  0,  0,  2, 10],
        [ 0,  0,  2, 10,  4],
        [ 0,  2, 10,  4, 11]], dtype=int32),
 array([ 5,  1,  3,  1,  4,  3,  1,  1,  6,  7,  8,  9, 10,  4, 11,  1]))

In [18]:
vocab_size=len(tokenizer.word_index)+1


In [19]:
vocab_size

12

Build a RNN model

In [20]:
model=Sequential([
    Embedding(vocab_size,10,input_length=X.shape[1]),
    SimpleRNN(32),
    Dense(vocab_size,activation="softmax")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="adam")

In [22]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 2.4585
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.4435
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2.4284
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.4129
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.3971
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 2.3809
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.3641
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.3467
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.3287
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2.3100
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 2.2906
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2705
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.2497
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 2.2282
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.2063
Epoch 16/100
1/1 ━━━━

In [23]:
input_text= "i am"
seq=tokenizer.texts_to_sequences(input_text)[0]  #tokenizer always returns a list of sequences
seq=pad_sequences([seq],maxlen=X.shape[1])
pred=model.predict(seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step


In [24]:
pred

array([[0.01634192, 0.07962783, 0.02211354, 0.08790212, 0.29834244,
        0.1545916 , 0.04609967, 0.04029115, 0.01332627, 0.00472038,
        0.19969179, 0.03695127]], dtype=float32)

In [25]:
pred_index=np.argmax(pred)

In [26]:
for word, index in tokenizer.word_index.items():
  if index==pred_index:
    print("Next word :",word)

Next word : like
