<a href="https://colab.research.google.com/github/Vivek-afk81/ml-workshop/blob/main/Transformer_HuggingFace_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Generation

In [1]:
# TEXT generation using gpt 2 from hugging face lib
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")  # the task you want to do and the model

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [2]:
prompt="what is deep learning"
output=pipe(prompt)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


In [3]:
print(output[0]["generated_text"])

what is deep learning?"

The team tried to figure out what the neural network would do if it were to recognize the user's actions, but the results were inconclusive.

"When we used our system to recognize a user's actions, we found that when we performed a mental action, it was more complete than before," says Michael J. Tamburello, a professor at Rutgers University who has led the research on deep learning. "We found that this is because the human brain is very different from a machine."

Using the Deep Learning Network in the lab

The team used a system developed by Carnegie Mellon University called the Deep Learning Network to recognize users' actions, and then compared their responses to the same neural network that was trained to recognize the user's actions. The system used a deep learning algorithm called Deep Convolutional Neural Networks, or DNN.

The program's task was to train the Deep Learning Network on a number of different tasks to learn a new action. If the system ident

Loading the model directly


In [4]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [5]:
tokenizer

GPT2Tokenizer(name_or_path='openai-community/gpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [32]:
#architecture of gpt2
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

### loading model directly from colab


In [33]:
from transformers import AutoTokenizer

In [34]:
tokenizer=AutoTokenizer.from_pretrained("gpt2")

In [35]:
sentence="step-by-step"
input_ids=tokenizer(sentence) #this will return a dictionary
#converting into tensors
input_ids=tokenizer(sentence,return_tensors="pt")
input_ids=input_ids['input_ids']

In [36]:
tokenizer.decode(input_ids[0])

'step-by-step'

In [37]:
sentence="unbelivable"
input_ids=tokenizer(sentence,return_tensors="pt").input_ids
input_ids

tensor([[  403,  6667, 21911]])

In [38]:
for token_id in input_ids[0]:
  print(tokenizer.decode(token_id))

un
bel
ivable


In [39]:
word="homoscedasticity"
my_ids=tokenizer.encode(word,return_tensors="pt")
my_ids

tensor([[26452,   418,   771,  3477,   414]])

In [40]:
word = "pneumonoultramicroscopicsilicovolcanoconiosis"
my_ids = tokenizer(word, return_tensors="pt").input_ids
len(my_ids[0])

15

In [41]:
for token_id in my_ids.squeeze():
  print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis


In [42]:
word = "floccinaucinihilipilification"

my_ids = tokenizer(word, return_tensors="pt").input_ids
my_ids, len(my_ids[0])

(tensor([[ 2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]]), 9)

In [43]:
for token_id in my_ids[0]:
  print(tokenizer.decode(token_id))

fl
occ
in
auc
in
ihil
ip
il
ification


### Generate using gpt2

In [57]:
from transformers import AutoModelForCausalLM
import torch

In [45]:
gpt2=AutoModelForCausalLM.from_pretrained("gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [56]:
sentence=" I learn machine learning to enhance the performance"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids

# print(gpt2(token_ids).logits.shape)
outputs=gpt2(token_ids).logits[0, -1]
tokenizer.decode(outputs.argmax())

' of'

In [65]:
sentence=" I learn machine learning to enhance the"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0, -1]
final_logits=torch.topk(outputs,7)
print(final_logits)

for index in final_logits.indices:
  print(tokenizer.decode(index))


torch.return_types.topk(
values=tensor([-110.0572, -110.1733, -110.5066, -110.7839, -110.9877, -111.2124,
        -111.2452], grad_fn=<TopkBackward0>),
indices=tensor([2854, 2836, 1692, 2694, 4673, 1998, 9332]))
 performance
 user
 human
 ability
 learning
 experience
 efficiency
