<a href="https://colab.research.google.com/github/Vivek-afk81/ml-workshop/blob/main/Transformer_HuggingFace_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Generation

In [2]:
# TEXT generation using gpt 2 from hugging face lib
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")  # the task you want to do and the model

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [3]:
prompt="what is deep learning"
output=pipe(prompt)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


In [4]:
print(output[0]["generated_text"])

what is deep learning? What is network learning?"

When asked this question, Mr. Li said, "I don't know. I don't know when they're going to come up with something."

For the next three years, Mr. Li and his colleagues at Stanford and MIT, working with the National Institute of Standards and Technology, began trying to work out the best approach for deep learning. They started with the idea that deep learning could be used to learn from the universe.

They were surprised to learn that something like this could be used to do this. There was some evidence that deep learning could be useful for some, but not for others. For example, in 2011, the journal Nature found that a group of people with neural networks were more likely than those without to learn from the universe.

In a 2013 paper, Mr. Li and his colleagues compared the neural networks of 2,000 people in the United States, Italy and France to those of 2,000 people in Britain.

Their findings were not surprising. It was the first ti

Loading the model directly


In [5]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [6]:
tokenizer

GPT2Tokenizer(name_or_path='openai-community/gpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
)

In [7]:
#architecture of gpt2
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

### loading model directly from colab


In [8]:
from transformers import AutoTokenizer

In [9]:
tokenizer=AutoTokenizer.from_pretrained("gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [10]:
sentence="step-by-step"
input_ids=tokenizer(sentence) #this will return a dictionary
#converting into tensors
input_ids=tokenizer(sentence,return_tensors="pt")
input_ids=input_ids['input_ids']

In [11]:
tokenizer.decode(input_ids[0])

'step-by-step'

In [12]:
sentence="unbelivable"
input_ids=tokenizer(sentence,return_tensors="pt").input_ids
input_ids

tensor([[  403,  6667, 21911]])

In [13]:
for token_id in input_ids[0]:
  print(tokenizer.decode(token_id))

un
bel
ivable


In [14]:
word="homoscedasticity"
my_ids=tokenizer.encode(word,return_tensors="pt")
my_ids

tensor([[26452,   418,   771,  3477,   414]])

In [15]:
word = "pneumonoultramicroscopicsilicovolcanoconiosis"
my_ids = tokenizer(word, return_tensors="pt").input_ids
len(my_ids[0])

15

In [16]:
for token_id in my_ids.squeeze():
  print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis


In [17]:
word = "floccinaucinihilipilification"

my_ids = tokenizer(word, return_tensors="pt").input_ids
my_ids, len(my_ids[0])

(tensor([[ 2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]]), 9)

In [18]:
for token_id in my_ids[0]:
  print(tokenizer.decode(token_id))

fl
occ
in
auc
in
ihil
ip
il
ification


### Generate using gpt2

In [27]:
from transformers import AutoModelForCausalLM
import torch
import torch.nn.functional as F

In [20]:
gpt2=AutoModelForCausalLM.from_pretrained("gpt2")

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [21]:
sentence=" I learn machine learning to enhance the performance"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids

# print(gpt2(token_ids).logits.shape)
outputs=gpt2(token_ids).logits[0, -1]
tokenizer.decode(outputs.argmax())

' of'

In [22]:
sentence=" I learn machine learning to enhance the"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0, -1]
final_logits=torch.topk(outputs,7)
print(final_logits)

for index in final_logits.indices:
  print(tokenizer.decode(index))


torch.return_types.topk(
values=tensor([-110.0572, -110.1733, -110.5066, -110.7839, -110.9877, -111.2124,
        -111.2452], grad_fn=<TopkBackward0>),
indices=tensor([2854, 2836, 1692, 2694, 4673, 1998, 9332]))
 performance
 user
 human
 ability
 learning
 experience
 efficiency


In [23]:
sentence="I learn machine learning to enhance"

token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0,-1]
tokenizer.decode(outputs.argmax())

' our'

### Sampling Techniques


In [26]:
print(gpt2(token_ids).logits.shape)

torch.Size([1, 6, 50257])


In [31]:
def greedy_decode(logits):
  """Return token index with maximum probablity"""
  return torch.argmax(logits,dim=-1) # dim =-1 because argmax() operate on the last dimension vocab


#TOP K SAMPLING

def top_k_sampling(logits,k=30):
  """keeps only top k logits,normalize them into probablity.
  then sample one token fro the filtered distribution"""

  #unpacking

  values,indices=torch.topk(logits,k)
  #torch.topk returns -> values: the top k highest logits, indices: their positions (token IDs)

  probs=F.softmax(values,dim=-1)
  sampled=torch.multinomial(probs,1)
  return indices[sampled]


# TOP-p SAMPLING

def top_p_sampling(logits,p=0.9):

  """sort the tokens by probablity keep smallest number whose  cumulative probablity exceeds threshold p,
    then sample one token"""
  sorted_logits,sorted_indices=torch.sort(logits,descending=True)
  sorted_probs=F.softmax(sorted_logits,dim=-1)
  cumulative_probs=sorted_probs.cumsum(dim=-1)

  #Mask token outside the threshold
  mask=cumulative_probs>p
  sorted_logits[mask]=float("-inf")

  #Sample rom filtered logits

  filtered_probs = F.softmax(sorted_logits,dim=-1)
  sampled=torch.multinomial(filtered_probs,1)

  # Return token index in originial vocabulary
  return sorted_indices[sampled]


#TEMPERATURE SAMPLING

"""
    Scale logits by temperature before sampling.
    Lower temperature => sharper distribution
"""

def temperature_sampling(logits, temperature=1.0):
  scaled= logits/temperature
  probs=F.softmax(scaled,dim=-1)
  return torch.multinomial(probs,1)


#RANDOM SAMPLING

def random_sampling(logits):
    """
    Sample dirctly from softmax distribution without filtring
    """

    probs = F.softmax(logits, dim=-1)
    return torch.multinomial(probs, 1)







In [34]:
sentence = "I am really happy becuase I have gone back in time.I"
inputs = tokenizer(sentence, return_tensors="pt")
output = gpt2(**inputs)
logits = output.logits[0, -1]

#outputs of different sampling strategies
print(f"Greedy Decode: ", tokenizer.decode([greedy_decode(logits)]))
print(f"Top-K Sampling: ", tokenizer.decode(top_k_sampling(logits, k=10)))
print(f"Top-P-Sampling: ", tokenizer.decode(top_p_sampling(logits, p=0.9)))
print(f"Temp: ", tokenizer.decode(temperature_sampling(logits, temperature=1)))
print(f"Random: ", tokenizer.decode(random_sampling(logits)))

Greedy Decode:   am
Top-K Sampling:   am
Top-P-Sampling:   have
Temp:   would
Random:   am
